### ISSUE TITLE
Regarding API interface to openbmc

### ISSUE THREAD

**Issue by ACodingfreak** [facebook/openbmc#89] opened 2018-07-18 18:48 UTC
Hi All,

I am quite new to openbmc and currently using wedge-100 switch in my lab.

I would like to know if there is any API guide for reference to access/modify the chassis level features provided in OPENBMC ? I tried digging into OpenBMC source code to find the REST API which is decent enough to get the information but I would like to control certain features likes FAN Speed and others from the C based application running in Main CPU via ethernet interface connected to BMC. Any reference application or link to the documentation would be of great help to play with openbmc.

By the way I am not sure if this is the right place to request the same, Please do point me to the right mailing list or community (if any) where I can request the same.

Thanks.

**Comment by benwei13** [comment] 2018-07-19 19:57
Hi @ajithadapa, the main interface for OpenBMC is ssh based.
if you're running an application from main CPU with ethernet connection to OpenBMC, for fan control (and other BMC utilities),  you may ssh into OpenBMC and then run commands such as "/usr/local/bin/fand --help"  to get more info on fan control

**Comment by marauderlabs** [comment] 2018-08-22 05:11
@ajithadapa Were you able to find the interface you were looking for? Am planning to do the same. A C program on the main CPU to fetch info about sensors/PSU etc

**Comment by ACodingfreak** [comment] 2018-08-24 03:13
@marauderlabs - I might stick with rest api for now but I am really looking for IPMI interface if available.

**Comment by sdasari73** [comment] 2018-09-05 22:50
>>I would like to control certain features likes FAN Speed
For fan control on wedge-100, you can tune the common fan algorithm with wedge specific configuration files (temp sensors/zones/pwm/linear/pid etc.) @ https://github.com/facebook/openbmc/tree/helium/meta-facebook/meta-wedge100/recipes-utils/fscd

**Comment by jda** [comment] 2019-08-03 00:43
Duplicate of #14 & #30

**Closed as completed by jda** 2019-08-03 00:43 UTC
